### ISSUE TITLE
CTRL + Enter to run

### ISSUE THREAD

**Issue by diegosouza** [matthisk/es6console#1]
Hello!

I've typed `console.log("print something");` on es6console.com and after typing CTRL + Enter the code is not executed. I've downloaded the source code and it seems the feature is implemented.

Is the website updated? Can you run code by pressing CTRL + Enter?

**Comment by matthisk** [comment]
Hi! Yes pressing CTRL + Enter is a feature of the website, I will investigate as to why this is broken right now.

**Comment by matthisk** [comment]
Hi! I have added functionality for running the input code on Ctrl-Enter if your cursor is positioned in the console.
